### ISSUE TITLE
Collaborating on UDS enums

### ISSUE THREAD

**Issue by nyurik** [japawBlob/uds-rs#1]
Hi, my [automotive_diag crate](https://github.com/nyurik/automotive_diag) implements all UDS and other enums that you may want to collaborate on - this way we have one common definition of all constants that all implementations can reuse.  Would you be interested in reusing it / joining our efforts? Thx!

**Comment by japawBlob** [comment]
Hey, cool. I created this library as part of my masters thesis and used it in one currently unpublished project. I currently do not have time to continue to work on my project, but I will sure redirect anyone looking to work on it to look at your implementation. Take care and good luck!

**Comment by nyurik** [comment]
Hi, sorry it took me a while to respond. The automotive_diag crate i mentioned has moved to a new home at [OxiBUS org](https://github.com/oxibus) -- where many volunteers are working on various low-level communication Rust crates.  Would you be interested in transfering your crate there as well? I will add you as a member to the org to make it easier, or if you want to participate in any other projects. Thx!
